[package]
name = "derivation-test"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "derivation-test"
path = "src/main.rs"

[dependencies]
kona-derive = { path = "../../crates/protocol/derive" }
kona-protocol = { path = "../../crates/protocol/protocol" }
kona-genesis = { path = "../../crates/protocol/genesis" }
kona-providers-alloy = { path = "../../crates/providers/providers-alloy" }
alloy-primitives = { workspace = true }
alloy-eips = { workspace = true }
alloy-provider = { workspace = true }
alloy-rpc-types-eth = { workspace = true }
op-alloy-network = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
eyre = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }